mysql:
  database: blog
  user: root
  password: 790461387
  url: localhost
  port: 3306
#redis配置
redis:
  host: localhost
  port: 6379
  password: 790461387
  database: 0
swagger:
  enable: true
# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    path: ./logs
